version: '3'
services:
  php:
    build: build/php
    expose:
      - "9000"
    depends_on:
      - mysql
    volumes:
      - ./symfony/assets:/var/www/symfony/assets:delegated
      - ./symfony/bin:/var/www/symfony/bin:delegated
      - ./symfony/bundles:/var/www/symfony/bundles:delegated
      - ./symfony/config:/var/www/symfony/config:delegated
      - ./symfony/dev:/var/www/symfony/dev:delegated
      - ./symfony/public:/var/www/symfony/public:delegated
      - ./symfony/src:/var/www/symfony/src:delegated
      - ./symfony/templates:/var/www/symfony/templates:delegated
      - ./symfony/tests:/var/www/symfony/tests:delegated
      - ./symfony/translations:/var/www/symfony/translations:delegated
      - ./symfony/var:/var/www/symfony/var:cached
      - ./symfony/vendor:/var/www/symfony/vendor:delegated
      - ./symfony/.env:/var/www/symfony/.env:delegated
      - ./symfony/composer.json:/var/www/symfony/composer.json:delegated
      - ./symfony/composer.lock:/var/www/symfony/composer.lock:cached
      - ./symfony/Makefile:/var/www/symfony/Makefile:delegated
      - ./symfony/package.json:/var/www/symfony/package.json:delegated
      - ./symfony/phpunit.xml.dist:/var/www/symfony/phpunit.xml.dist:delegated
      - ./symfony/symfony.lock:/var/www/symfony/symfony.lock:cached
      - ./symfony/webpack.config.js:/var/www/symfony/webpack.config.js:delegated
      - ./symfony/yarn.lock:/var/www/symfony/yarn.lock:cached
      - ./logs:/var/log:cached

  nginx:
    build: build/nginx
    restart: always
    ports:
      - "81:80"
    depends_on:
      - php
      - mysql
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs:/var/log/nginx:cached

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    ports:
      - "3308:3306"
    volumes:
      - ./var/mysql:/var/lib/mysql:cached
